/** @type {import('tailwindcss').Config} */
/**
 * Tokens live in src/styles/tokens.css as CSS custom properties and are
 * surfaced here by name. Never write a raw hex value in a component —
 * every colour, radius, shadow and space step below has a Figma twin.
 */
module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        /* --- primitives --- */
        panel: {
          400: 'var(--color-panel-400)',
          500: 'var(--color-panel-500)',
          600: 'var(--color-panel-600)',
          700: 'var(--color-panel-700)',
          800: 'var(--color-panel-800)',
          900: 'var(--color-panel-900)',
        },
        solar: {
          50: 'var(--color-solar-50)',
          100: 'var(--color-solar-100)',
          200: 'var(--color-solar-200)',
          300: 'var(--color-solar-300)',
          400: 'var(--color-solar-400)',
          500: 'var(--color-solar-500)',
          600: 'var(--color-solar-600)',
          700: 'var(--color-solar-700)',
          800: 'var(--color-solar-800)',
        },
        sunset: {
          50: 'var(--color-sunset-50)',
          100: 'var(--color-sunset-100)',
          200: 'var(--color-sunset-200)',
          300: 'var(--color-sunset-300)',
          400: 'var(--color-sunset-400)',
          500: 'var(--color-sunset-500)',
          600: 'var(--color-sunset-600)',
          700: 'var(--color-sunset-700)',
        },
        dusk: {
          50: 'var(--color-dusk-50)',
          100: 'var(--color-dusk-100)',
          200: 'var(--color-dusk-200)',
          300: 'var(--color-dusk-300)',
          400: 'var(--color-dusk-400)',
          500: 'var(--color-dusk-500)',
          600: 'var(--color-dusk-600)',
          700: 'var(--color-dusk-700)',
        },
        sage: {
          50: 'var(--color-sage-50)',
          100: 'var(--color-sage-100)',
          200: 'var(--color-sage-200)',
          300: 'var(--color-sage-300)',
          400: 'var(--color-sage-400)',
          500: 'var(--color-sage-500)',
          600: 'var(--color-sage-600)',
          700: 'var(--color-sage-700)',
        },
        sand: {
          0: 'var(--color-neutral-0)',
          50: 'var(--color-neutral-50)',
          100: 'var(--color-neutral-100)',
          150: 'var(--color-neutral-150)',
          200: 'var(--color-neutral-200)',
          300: 'var(--color-neutral-300)',
          400: 'var(--color-neutral-400)',
          500: 'var(--color-neutral-500)',
          600: 'var(--color-neutral-600)',
          700: 'var(--color-neutral-700)',
          800: 'var(--color-neutral-800)',
          900: 'var(--color-neutral-900)',
        },
        danger: {
          100: 'var(--color-danger-100)',
          300: 'var(--color-danger-300)',
          500: 'var(--color-danger-500)',
          600: 'var(--color-danger-600)',
          900: 'var(--color-danger-900)',
        },

        /* --- semantic aliases: prefer these in components --- */
        bg: {
          page: 'var(--bg-page)',
          subtle: 'var(--bg-subtle)',
          surface: 'var(--bg-surface)',
          inverse: 'var(--bg-inverse)',
          'panel-deep': 'var(--bg-panel-deep)',
          'panel-raised': 'var(--bg-panel-raised)',
        },
        content: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          tertiary: 'var(--text-tertiary)',
          'on-brand': 'var(--text-on-brand)',
          'on-dark': 'var(--text-on-dark)',
          'on-dark-muted': 'var(--text-on-dark-muted)',
          brand: 'var(--text-brand)',
          disabled: 'var(--text-disabled)',
        },
        line: {
          subtle: 'var(--border-subtle)',
          DEFAULT: 'var(--border-default)',
          strong: 'var(--border-strong)',
          brand: 'var(--border-brand)',
          'on-dark': 'var(--border-on-dark)',
        },
      },
      fontFamily: {
        /* `font-sans` follows the active language; the other two are escapes
           for the brand lockup and for explicitly Arabic runs. */
        sans: ['var(--font-active)', 'system-ui', 'sans-serif'],
        latin: ['var(--font-sans)', 'system-ui', 'sans-serif'],
        arabic: ['var(--font-arabic)', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['var(--fs-display-xl)', { lineHeight: 'var(--lh-display-xl)', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-l': ['var(--fs-display-l)', { lineHeight: 'var(--lh-display-l)', letterSpacing: '-0.015em', fontWeight: '600' }],
        h1: ['var(--fs-h1)', { lineHeight: 'var(--lh-h1)', letterSpacing: '-0.015em', fontWeight: '600' }],
        h2: ['var(--fs-h2)', { lineHeight: 'var(--lh-h2)', letterSpacing: '-0.01em', fontWeight: '600' }],
        h3: ['var(--fs-h3)', { lineHeight: 'var(--lh-h3)', letterSpacing: '-0.005em', fontWeight: '600' }],
        h4: ['var(--fs-h4)', { lineHeight: 'var(--lh-h4)', letterSpacing: '-0.0025em', fontWeight: '500' }],
        'body-lg': ['1.125rem', { lineHeight: '1.75rem' }],
        body: ['1rem', { lineHeight: '1.625rem' }],
        'body-sm': ['0.875rem', { lineHeight: '1.375rem' }],
        label: ['0.875rem', { lineHeight: '1.25rem', fontWeight: '500' }],
        'label-sm': ['0.75rem', { lineHeight: '1rem', fontWeight: '500' }],
        overline: ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.08em', fontWeight: '600' }],
        'data-xl': ['2.25rem', { lineHeight: '2.5rem', letterSpacing: '-0.01em', fontWeight: '600' }],
        'data-l': ['1.75rem', { lineHeight: '2.125rem', letterSpacing: '-0.005em', fontWeight: '600' }],
      },
      spacing: {
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        8: 'var(--space-8)',
        10: 'var(--space-10)',
        12: 'var(--space-12)',
        16: 'var(--space-16)',
        20: 'var(--space-20)',
        24: 'var(--space-24)',
        30: 'var(--space-30)',
      },
      borderRadius: {
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius-md)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        full: '9999px',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow-md)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        glow: 'var(--shadow-glow)',
        panel: 'var(--shadow-panel)',
      },
      maxWidth: {
        container: 'var(--container-max)',
      },
    },
  },
  plugins: [],
};
